services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: stream-tube-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB:-streamtube}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-streamtube}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-streamtube}
      - SPRING_DOCKER_COMPOSE_ENABLED=false
    depends_on:
      db:
        condition: service_healthy
    networks:
      - stream-tube-network

  db:
    image: 'postgres:17-alpine'
    container_name: stream-tube-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-streamtube}
      - POSTGRES_USER=${POSTGRES_USER:-streamtube}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-streamtube}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-streamtube}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stream-tube-network

volumes:
  postgres_data:

networks:
  stream-tube-network:
    driver: bridge
