spring:
  datasource:
    url: jdbc:postgresql://db:5432/streamtube
    username: ${POSTGRES_USER:streamtube}
    password: ${POSTGRES_PASSWORD:streamtube}
  docker:
    compose:
      enabled: false
  mail:
    host: mailpit
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

streamtube:
  security:
    jwt:
      private-key: |
        -----BEGIN PRIVATE KEY-----
        ---
        -----END PRIVATE KEY-----
      public-key: |
        -----BEGIN PUBLIC KEY-----
        ---
        -----END PUBLIC KEY-----

streamtube:
  app:
    public-url: http://localhost:8080
