spring:
  docker:
    compose:
      enabled: false
  mail:
    host: localhost
    port: 1025

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: WARN

streamtube:
  security:
    jwt:
      private-key: |
        -----BEGIN PRIVATE KEY-----
        ---
        -----END PRIVATE KEY-----
      public-key: |
        -----BEGIN PUBLIC KEY-----
        ---
        -----END PUBLIC KEY-----
