spring:
  datasource:
    url: jdbc:postgresql://db:5432/streamtube
    username: ${POSTGRES_USER:streamtube}
    password: ${POSTGRES_PASSWORD:streamtube}
  docker:
    compose:
      enabled: false
