spring:
  application:
    name: stream-tube-backend
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  error:
    include-message: never
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when-authorized

streamtube:
  ratelimit:
    auth:
      limit-for-period: 10
      limit-refresh-period: 1m
      timeout-duration: 0s

logging:
  level:
    root: INFO
